import { Travel } from "../../../model/Travel";

export const travelsFactory = [
  new Travel({
    id: 1,
    name: "Tour du Mont Blanc",
    duration: 10,
    start_date: "",
    end_date: "",
    stepsNumber: 8,
    is_public: true,
    is_album_public: true,
    path_uid: "",
    commentary: "",
    path: require("../../../img/static/publicTravels/montBlanc.jpg"),
    id_traveltag: 4,
  }),
  new Travel({
    id: 2,
    name: "Voyage au Japon",
    duration: 15,
    start_date: "",
    end_date: "",
    stepsNumber: 10,
    is_public: true,
    is_album_public: true,
    path_uid: "",
    commentary: "",
    path: require("../../../img/static/publicTravels/japon.jpg"),
    id_traveltag: 10,
  }),
  new Travel({
    id: 3,
    name: "Escapade à New York",
    duration: 8,
    start_date: "",
    end_date: "",
    stepsNumber: 8,
    is_public: true,
    is_album_public: true,
    path_uid: "",
    commentary: "",
    path: require("../../../img/static/publicTravels/nyc.jpg"),
    id_traveltag: 3,
  }),
  new Travel({
    id: 4,
    name: "Tour d'Europe",
    duration: 180,
    start_date: "",
    end_date: "",
    stepsNumber: 100,
    is_public: true,
    is_album_public: true,
    path_uid: "",
    commentary: "",
    path: require("../../../img/static/publicTravels/europe.jpg"),
    id_traveltag: 5,
  }),
  new Travel({
    id: 5,
    name: "Road Trip au Maroc",
    duration: 60,
    start_date: "",
    end_date: "",
    stepsNumber: 25,
    is_public: true,
    is_album_public: true,
    path_uid: "",
    commentary: "",
    path: require("../../../img/static/publicTravels/maroc.jpg"),
    id_traveltag: 3,
  }),
  new Travel({
    id: 6,
    name: "Tour des abbayes de France",
    duration: 10,
    start_date: "",
    end_date: "",
    stepsNumber: 8,
    is_public: true,
    is_album_public: true,
    path_uid: "",
    commentary: "",
    path: require("../../../img/static/publicTravels/abbaye.jpg"),
    id_traveltag: 6,
  }),
];
